// index1
[
'Revolver Anodyne',
'Revolver The Mandarin',
'Revolver Sangre Y Miel',
'Revolver Fracker Barrel One',
'Saint Arnold Raspberry AF',
'Saint Arnold Art Car IPA',
'Saint Arnold Pub Crawl',
'Sam Adams Wild Child American Sour',
'Sam Adams Rebel Juiced IPA',
'Sam Adams Summer Ale',
'Schilling Grapefruit &amp; Chill',
'Schilling London Dry',
'Schilling Passport: Passionfruit Pineapple',
'Schilling Emerald City; Blackberry Pear',
'Shiner Ruby Redbird',
'Shiner Bock',
'Shiner Berliner Weiss',
'Shiner Homespun Cream Ale',
'Shiner Strawberry Blonde',
'Shiner Shiner Light Blonde',
'Sierra Nevada Narwhal',
'Sierra Nevada Chocolate Cherry Stout',
'Sierra Nevada Tropical Torpedo',
'Sierra Nevada Sidecar Orange Pale Ale',
'South Austin ',
'South Austin ',
'South Austin ',
'Stone Ripper',
]

// index2
[
'Stone Tangerine Express',
'Stone Jindia Pale Ale',
'Stone Dayslayer',
'Stone 2015 Double Bastard',
'Sweetwater 420 Extra Pale Ale',
'Sweetwater Goin\' Coastal Pineapple IPA',
'Sweetwater Cool Breeze Cucumber Saison',
'Sweetwater Sweetwater IPA',
'Sweetwater Pulled Porter Smoked Bacon Porter',
'Thirsty Planet Thirsty Goat',
'Thirsty Planet Bucket Head',
'Thirsty Planet ChiGoatle',
'Treaty Oak Lil Hop IPA'
]

// index3
[
'Treaty Oak Brightside Blonde',
'Treaty Oak Fitzhugh Mild',
'Twisted X Hy-Biscus',
'Twisted X Midnight Magician',
'Twisted X Austin Lager',
'Twisted X Chupahopra',
'Twisted X Cow Creek',
'Twisted X Later Days',
'Uncle Billy\'s Green Room',
'Uncle Billy\'s Lazy Day',
'Uncle Billy\'s Lust for Life',
'Unibroue A Tout le Monde',
'Unibroue 17 Grande Reserve',
'Unibroue La Fin du Monde',
'Unibroue Ephemere Elderberry',
'Victory  Blackboard Series No. 5',
'Victory  Summer Love',
'Victory  Sour Monkey',
'Victory  Golden Monkey',
];