module.exports = [
'Ommegang Great Beyond',
'Ommegang Rosetta',
'Ommegang Witte',
'Ommegang Duvel Triple',
'Ommegang Fruition',
'Oskar Blues Dale\'s',
'Oskar Blues Pinner',
'Oskar Blues Beerito',
'Oskar Blues Fugli',
'Oskar Blues IPA',
'Pedernales Bitter Battle',
'Pedernales Robert Earl Keen Front Porch',
'Pedernales Texas Lager',
'Peticolas Velvet Hammer',
'Peticolas Sit Down Or I\'ll Sit You Down',
'Peticolas Thrilla in Brazilla',
'Pinthouse Pizza Electric Jellyfish',
'Pinthouse Pizza Burro\'s Breakfast',
'Pinthouse Pizza Handlebier',
'Pinthouse Pizza Joe\'s Magical Pils',
'Pinthouse Pizza Old Beluga',
'Pinthouse Pizza Zappy Squid IPA',
'Rabbit Hole Rapture',
'Rabbit Hole Off With Your Red',
'Rabbit Hole JabberBOCK',
'Rahr & Sons Dadgum IPA',
'Rahr & Sons Summertime Wheat',
'Rahr & Sons Midnight Cab BA',
'Revolver Blood & Honey',
'Revolver Sidewinder',
'Revolver Ironhead',
'Revolver Bock',
'Revolver High Brass',
'Revolver Full Tang',
'Revolver Anodyne',
'Revolver The Mandarin',
'Revolver Sangre Y Miel',
'Revolver Fracker Barrel One',
];